package util

data class Language(val code: String, val name: String) {
    companion object {
        fun getAll() = listOf(
            Language("en", "English"),
            Language("es", "Spanish"),
            Language("fr", "French"),
            Language("de", "German"),
            Language("zh", "Chinese"),
            Language("ar", "Arabic"),
            Language("ru", "Russian"),
            Language("it", "Italian"),
            Language("ja", "Japanese"),
            Language("ko", "Korean"),
            Language("hi", "Hindi"),
            Language("bn", "Bengali"),
            Language("pa", "Punjabi"),
            Language("ur", "Urdu"),
            Language("vi", "Vietnamese"),
            Language("th", "Thai"),
            Language("tr", "Turkish"),
            Language("pl", "Polish"),
            Language("nl", "Dutch"),
            Language("sv", "Swedish"),
            Language("no", "Norwegian"),
            Language("da", "Danish"),
            Language("fi", "Finnish"),
            Language("el", "Greek"),
            Language("cs", "Czech"),
            Language("hu", "Hungarian"),
            Language("ro", "Romanian"),
            Language("zh-Hans", "Chinese (Simplified)"),
            Language("zh-Hant", "Chinese (Traditional)"),
            Language("pt-BR", "Portuguese (Brazil)"),
            Language("pt-PT", "Portuguese (Portugal)"),
            Language("sr-Latn", "Serbian (Latin)"),
            Language("sr-Cyrl", "Serbian (Cyrillic)"),
            Language("es-419", "Spanish (Latin America)"),
            Language("nan-Hant-TW", "Min Nan (Taiwan)"),
            Language("yue-Hant-HK", "Cantonese (Hong Kong)"),
            Language("el", "Greek"),
            Language("he", "Hebrew"),
            Language("ms", "Malay"),
            Language("id", "Indonesian"),
            Language("ta", "Tamil"),
            Language("kn", "Kannada"),
            Language("mr", "Marathi"),
            Language("te", "Telugu"),
            Language("ml", "Malayalam"),
            Language("gu", "Gujarati"),
            Language("si", "Sinhalese"),
            Language("ur", "Urdu"),
            Language("fa", "Persian"),
            Language("af", "Afrikaans"),
            Language("sw", "Swahili"),
            Language("zu", "Zulu"),
            Language("xh", "Xhosa"),
            Language("ht", "Haitian Creole"),
            Language("eu", "Basque"),
            Language("ga", "Irish"),
            Language("cy", "Welsh"),
            Language("sq", "Albanian"),
            Language("sr", "Serbian (generic)"),
            Language("mk", "Macedonian"),
            Language("bg", "Bulgarian"),
            Language("uk", "Ukrainian"),
            Language("be", "Belarusian"),
            Language("sk", "Slovak"),
            Language("sl", "Slovenian"),
            Language("hr", "Croatian"),
            Language("sr", "Serbian"),
            Language("bs", "Bosnian")
            // Add more as necessary...

        )

        val defaultSource = getAll()[0]
        val defaultTarget = getAll()[1]
    }
}
